---
- hosts: node1
  connection: ssh
  sudo: yes
  tasks:
   - name: Install httpd
     yum: pkg=httpd state=installed
     ignore_errors: yes
   - name: copy index.html
     copy: src=index.html dest=/var/www/html/index.html
     ignore_errors: yes
     notify: now start the service
   - name: start httpd service
     service: name=httpd state=started 
