---
- hosts: node1
  connection: ssh
  sudo: yes
  tasks:
   - name: install httpd
     yum: name=httpd state=installed
   - name: copy index.html 
     copy: src=index.html dest=/var/www/html/index.html
   - name: start httpd service
     service: name=httpd state=started
