---
- hosts: node1
  connection: ssh
  sudo: yes
  vars:
   pkg: httpd
  tasks:
   - name: install {{httpd}}
     yum: name={{pkg}} state=installed
   - name: uninstall {{pkg}}
     yum: name={{pkg}} state=removed
